### ISSUE TITLE
anxious to see where this goes...

### ISSUE THREAD

**Issue by jfrux** [brian-mann/rails-generators#2]
I'm dying to learn good ways to handle marionette within rails and having generators would be a much quicker way to get up and running and understand it.

I've generated an app with your script but not sure how to use your generators.

I know you aren't "there" yet, just figured I'd try it out.

Thanks again!

**Comment by brian-mann** [comment]
I've worked on this recently and documented a lot more of the generator actions.  These are **really** customized to my process but it's starting to come together.  There's a lot more configuration for base classes, module creation, controller creation, view creation, templates, and entities (models and collections).
